name: TSProjectGenerator
kind: pipeline
type: docker

steps:
  - name: install
    image: mcr.microsoft.com/powershell
    volumes:
      - name: au
        path: /usr/local/share/powershell/Modules
    commands:
      - apt install p7zip-full
      - git clone -q https://github.com/majkinetor/au.git /tmp/au
      - sed -i s/\b\\\b/\//g /tmp/au/scripts/Create-ModuleManifest.ps1
      - sed -i s/\b\\\*/\/*/g /tmp/au/scripts/Create-ModuleManifest.ps1
      - sed -i s/\b\\\$/\/$/g /tmp/au/build.ps1
      - sed -i 's/"\$Env:ProgramFiles\\WindowsPowerShell\\Modules"/"/\/usr\/local\/share\/powershell\/Modules"/g' /tmp/au/install.ps1
      - sed -i s/\b\\\$/\/$/g /tmp/au/install.ps1
      - sed -i 's/\b\\\b/\//g' /tmp/au/AU/Private/AUPackage.ps1
      - sed -i 's/\b\\\*/\/*/g' /tmp/au/AU/Private/AUPackage.ps1
      - sed -i 's/\b\\"/\//g' /tmp/au/AU/Private/AUPackage.ps1
      - sed -i 's/\}\\\{/}/{/g' /tmp/au/AU/Private/AUPackage.ps1
      - sed -i 's/\b\\\\\"/\/\"/g' /tmp/au/AU/Private/AUPackage.ps1
      - sed -i 's/}\\{/}\/{/g' /tmp/au/AU/Private/AUPackage.ps1
      - |
        pwsh -c "
            function makedir { pwsh -c ""New-Item -Type Directory $args"" }
            Set-Alias 'sort' 'Sort-Object'
            Set-Alias 'rm' 'Remove-Item'
            Set-Alias 'mkdir' 'makedir'
            Set-Alias 'ls' 'Get-ChildItem'
            Set-Alias 'cp' 'Copy-Item'
            Set-Alias '/tools/7z.exe' '7z'
            /tmp/au/scripts/Install-AU.ps1"
  - name: test
    image: mcr.microsoft.com/powershell
    environment:
      au_test_groups: "1"
    volumes:
      - name: au
        path: /usr/local/share/powershell/Modules
    commands:
      - pwsh ./test_all.ps1 "random $Env:au_test_groups"
  - name: test
    image: mcr.microsoft.com/powershell
    environment:
      au_push: "true"
      au_test_groups: "1"
      github_user_repo: "manuth/RaymanControlPanel-Choco"
      github_api_key:
        from_secret: github_token
      gist_id: 0ebf931dfdb7df45e2f01d01757582b0
      gist_id_test: 329ced3a8b6e52d83da64f7a9630f527
      api_key:
        from_secret: choco_apikey
    volumes:
      - name: au
        path: /usr/local/share/powershell/Modules
    commands:
      - apt install p7zip-full
      - pwsh ./update_all.ps1

trigger:
  ref:
    - refs/heads/**
    - refs/pull/**
    - refs/tags/**
  event:
    - push
    - pull_request
    - tag

volumes:
  - name: au
    temp: {}
